---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-frontends-flaskapp
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/dmilet/homelab-deployments.git
        revision: HEAD
        files:
          - path: applicationsets/dev/**/config.yaml
  template:
    metadata:
      name: dev-frontends-flaskapp-oci
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.events-aggregator: ""
        notifications.argoproj.io/subscribe.on-sync-running.events-aggregator: ""
      labels:
        appversion: '{{ .config.chart.version }}'
        deploymentid: '{{ default "manual" .deploymentid }}'
    spec:
      syncPolicy:
        automated:
          prune: true
      destination:
        # app will be in dev namespace, in dev project
        namespace: dev
        server: https://kubernetes.default.svc
      project: dev
      sources:
        - repoURL: https://github.com/dmilet/homelab-deployments.git
          targetRevision: HEAD
          ref: values
        - repoURL: registry-1.docker.io/davidmilet
          targetRevision: '{{ .config.chart.version }}'
          chart: '{{ .config.chart.name }}'
          helm:
            valueFiles:
              - $values/envs/common/frontend.yaml
              - $values/envs/dev/frontend.yaml
              - $values/values/dev/frontend.yaml