apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-frontends-flaskapp-git
  # ArgoCD is in "argocd" namespace in this cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.events-aggregator: ""
    notifications.argoproj.io/subscribe.on-sync-running.events-aggregator: ""
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    # app will be in dev namespace, in dev project
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  sources:
    - repoURL: https://github.com/dmilet/homelab-deployments.git
      targetRevision: HEAD
      ref: values

    - repoURL: https://github.com/dmilet/homelab-deployments.git
      targetRevision: HEAD
      path: charts/frontends/flaskapp
      helm:
        valueFiles: 
          - $values/envs/common/frontend.yaml
          - $values/envs/dev/frontend.yaml
          - $values/values/dev/frontend.yaml