apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-svc
  namespace: dev
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ template "fullname" . }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
