apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-bitnami-postgres-oci
  # ArgoCD is in "argocd" namespace in this cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # app will be in postgres namespace, in lab project
    namespace: postgres
    server: {{ .Values.spec.destination.server }}
  project: lab
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values

    - repoURL: registry-1.docker.io/bitnamicharts
      path: bitnamicharts
      targetRevision: 15.2.5
      chart: postgresql
      helm:
        valueFiles: 
          - $values/envs/common/postgres.yaml
          - $values/envs/lab/postgres.yaml
          - $values/values/lab/frontend.yaml