apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-nxrm-busybox-git
  # ArgoCD is in "argocd" namespace in this cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # app will be in postgres namespace, in lab project
    namespace: nxrm
    server: {{ .Values.spec.destination.server }}
  project: lab
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values

    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: charts/lab/busybox
      helm:
        valueFiles: 
          - $values/envs/common/busybox.yaml
          #- $values/envs/lab/busybox.yaml
          #- $values/values/lab/busybox.yaml

