---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-frontends-flaskapp
  namespace: argocd
spec:
  #goTemplate: true
  #goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/dmilet/homelab-deployments.git 
        revision: HEAD
        files:
          - path: applicationsets/dev/**/config.yaml
  template:
    metadata:
      name: dev-frontends-flaskapp-oci
      namespace: argocd
      labels:
        swift.io/createdby: applicationset
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.events-aggregator: ""
        notifications.argoproj.io/subscribe.on-sync-running.events-aggregator: ""
    spec:
      syncPolicy:
        automated:
          prune: true
      destination:
        # app will be in dev namespace, in dev project
        namespace: dev
        server: '{{ .Values.spec.destination.server }}'
      project: dev
      sources:
        - repoURL: '{{ .Values.spec.source.repoURL }}'
          targetRevision: '{{ .Values.spec.source.targetRevision }}'
          ref: values
        - repoURL: registry-1.docker.io/davidmilet
          targetRevision: '{{.config.chart.version}}'
          chart: '{{.config.chart.name}}'
          helm:
            valueFiles:
              - $values/envs/common/frontend.yaml
              - $values/envs/dev/frontend.yaml
              - $values/values/dev/frontend.yaml