apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-frontends-flaskapp-oci
  # ArgoCD is in "argocd" namespace in this cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    # app will be in dev namespace, in dev project
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: dev
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values

    - repoURL: kali-pf37qnb7:444
      path: davidmilet/frontends-flaskapp
      targetRevision: '*'
      chart: frontends-flaskapp
      helm:
        valueFiles: 
          - $values/envs/common/frontend.yaml
          - $values/envs/dev/frontend.yaml
          - $values/values/dev/frontend.yaml