apiVersion: v1
kind: Service
metadata:
  name: lab-nxrm-nexusrepo
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
  namespace: nxrm
spec:
  ports:
    - name: tcp-nexusrepo
      nodePort: null
      port: 8081
      targetPort: tcp-nxrm
    - name: tcp-nexusrepo-ssl
      nodePort: null
      port: 443
      targetPort: tcp-nxrm-ssl
    - name: tcp-nexusrepo-docker
      nodePort: null
      port: 444
      targetPort: tcp-nxrm-docker
  selector:
    app: {{ template "fullname" . }}
  sessionAffinity: None
  type: ClusterIP
